// <auto-generated />
namespace interview_log.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class InfoFieldForUserAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InfoFieldForUserAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201403260944329_InfoFieldForUserAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
